import Link from "next/link";

import { AppShell } from "@/components/dashboard/app-shell";
import { DashboardSection, EmptyState, MetricCard } from "@/components/dashboard/dashboard-primitives";
import { NotificationFeed } from "@/components/dashboard/notification-feed";
import { NotificationPreferenceForm } from "@/components/dashboard/notification-preference-form";
import { ParentLinkForm } from "@/components/dashboard/parent-link-form";
import { getParentLinkedQuizResults } from "@/lib/assessments/queries";
import { assertRole } from "@/lib/auth/roles";
import {
  getParentAccessibleProgramSummaries,
  getParentChildTaskDeadlines,
  getParentLinkedChildren,
  getParentSummary,
  getProfileForCurrentUser,
  getUserNotifications,
  getUserNotificationPreferences,
  getUserNotificationUnreadCount,
  getUserPurchases
} from "@/lib/dashboard/queries";
import { formatDate } from "@/lib/format";
import type { NotificationPreferenceRecord, NotificationRecord } from "@/types/domain";

export default async function ParentDashboardPage() {
  const { profile, user } = await getProfileForCurrentUser();
  assertRole(["parent", "admin"], profile?.role ?? null);

  let notifications: NotificationRecord[] = [];
  let notificationError: string | null = null;
  let unreadNotificationCount = 0;
  let notificationPreferences: NotificationPreferenceRecord[] = [];
  if (profile?.role === "parent") {
    try {
      [notifications, unreadNotificationCount, notificationPreferences] = await Promise.all([
        getUserNotifications(user!.id),
        getUserNotificationUnreadCount(user!.id),
        getUserNotificationPreferences(user!.id, "parent")
      ]);
    } catch (error) {
      notificationError = (error as Error).message;
    }
  }

  const [summary, linkedChildren, programs, purchases, childDeadlines, linkedQuizResults] = await Promise.all([
    getParentSummary(user!.id),
    getParentLinkedChildren(user!.id),
    getParentAccessibleProgramSummaries(user!.id),
    getUserPurchases(user!.id),
    getParentChildTaskDeadlines(user!.id),
    getParentLinkedQuizResults(user!.id)
  ]);

  return (
    <AppShell
      role="parent"
      title="Parent dashboard"
      description="Parents can monitor linked child progress, review recent project and assessment activity, purchase programs, and book consultations."
      unreadNotificationCount={unreadNotificationCount}
    >
      <section className="grid gap-4 md:grid-cols-2">
        <MetricCard label="Purchases synced" value={String(summary.purchaseCount)} detail="Shopify purchases will show up here after webhook sync." />
        <MetricCard
          label="Active enrollments"
          value={String(summary.enrollmentCount)}
          detail={`${linkedChildren.length} linked child account${linkedChildren.length === 1 ? "" : "s"} visible here.`}
        />
      </section>

      <DashboardSection
        title="Family alerts"
        description="Read-only due-soon and overdue summaries for linked learners are generated by the scheduled reminder system from the same deadlines students and teachers see."
      >
        {profile?.role === "admin" ? (
          <EmptyState title="Admin account in parent view" description="Parent reminder summaries only generate for real parent accounts with linked learners." />
        ) : notificationError ? (
          <div className="rounded-[1.5rem] border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">
            Parent summaries could not be loaded right now: {notificationError}
          </div>
        ) : (
          <NotificationFeed notifications={notifications} emptyLabel="No family deadline summaries are active right now." />
        )}
      </DashboardSection>

      {profile?.role === "parent" ? (
        <DashboardSection
          title="Summary preferences"
          description="Control whether family summaries appear in-app or by email for your account."
        >
          {notificationPreferences.length === 0 ? (
            <EmptyState title="No summary preferences available" description="If parent summary types have been disabled globally, there may be nothing to configure here yet." />
          ) : (
            <div className="grid gap-4 xl:grid-cols-2">
              {notificationPreferences.map((preference) => (
                <NotificationPreferenceForm key={preference.type} preference={preference} />
              ))}
            </div>
          )}
        </DashboardSection>
      ) : null}

      <DashboardSection
        title="Link a child account"
        description="Enter the email address used for the student account to connect parent visibility."
      >
        <ParentLinkForm />
      </DashboardSection>

      <DashboardSection
        className="scroll-mt-24"
        title="Programs and purchases"
        description="Parents can see which programs are unlocked directly, which are available through linked children, and how recent purchases were processed."
      >
        <div id="programs" className="grid gap-4 xl:grid-cols-2">
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-ink">Accessible programs</h3>
            {programs.length === 0 ? (
              <EmptyState
                title="No program access yet"
                description="Once a purchase is matched or a linked child is enrolled, accessible programs will appear here."
              />
            ) : (
              programs.map((program) => (
                <article key={program.id} className="rounded-[1.5rem] border border-slate-200 p-5">
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <h4 className="text-lg font-semibold text-ink">{program.title}</h4>
                      <p className="mt-2 text-sm leading-6 text-slate-700">{program.description}</p>
                    </div>
                    <span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">
                      {program.progressPercent}% complete
                    </span>
                  </div>
                  <p className="mt-3 text-sm text-slate-500">{program.accessLabel}</p>
                  <p className="mt-2 text-sm text-slate-600">
                    {program.completedLessonCount} of {program.lessonCount} lessons completed.
                    {program.nextLessonTitle ? ` Next recommended lesson: ${program.nextLessonTitle}.` : ""}
                  </p>
                  <Link
                    href={`/app/programs/${program.slug}`}
                    className="mt-4 inline-flex rounded-full border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 transition hover:border-brand-300 hover:text-brand-900"
                  >
                    Open program view
                  </Link>
                </article>
              ))
            )}
          </div>
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-ink">Recent purchases</h3>
            {purchases.length === 0 ? (
              <EmptyState
                title="No purchases synced yet"
                description="Shopify purchases will appear here after webhook processing."
              />
            ) : (
              purchases.map((purchase) => (
                <article key={purchase.id} className="rounded-[1.5rem] border border-slate-200 p-5">
                  <p className="text-sm font-semibold text-ink">Order {purchase.orderId}</p>
                  <p className="mt-2 text-sm text-slate-600">
                    {purchase.processingState} | {purchase.financialStatus}
                  </p>
                  {purchase.processingError ? <p className="mt-2 text-sm text-amber-700">{purchase.processingError}</p> : null}
                </article>
              ))
            )}
          </div>
        </div>
      </DashboardSection>

      <DashboardSection
        className="scroll-mt-24"
        title="Linked child progress"
        description="Parents can monitor project activity, feedback volume, and assessment outcomes for linked learner accounts."
      >
        <div id="progress">
          {linkedChildren.length === 0 ? (
            <EmptyState
              title="No child accounts linked yet"
              description="Use the link form above to connect a student account and unlock parent visibility."
            />
          ) : (
            <div className="grid gap-4 xl:grid-cols-2">
              {linkedChildren.map((child) => (
                <article key={child.studentId} className="rounded-[1.5rem] border border-slate-200 p-5">
                  <h3 className="text-xl font-semibold text-ink">{child.studentName}</h3>
                  <div className="mt-4 grid gap-3 sm:grid-cols-2">
                    <div className="rounded-3xl bg-slate-50 p-4">
                      <p className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-500">Projects</p>
                      <p className="mt-2 text-2xl font-semibold text-ink">{child.projectCount}</p>
                      <p className="mt-2 text-sm text-slate-600">{child.latestProjectTitle ?? "No project submitted yet."}</p>
                    </div>
                    <div className="rounded-3xl bg-brand-50 p-4">
                      <p className="text-xs font-semibold uppercase tracking-[0.24em] text-brand-700">Assessments</p>
                      <p className="mt-2 text-2xl font-semibold text-brand-900">
                        {child.averageAssessmentScore !== null ? `${child.averageAssessmentScore.toFixed(1)}%` : "Pending"}
                      </p>
                      <p className="mt-2 text-sm text-brand-900">{child.latestAssessmentTitle ?? "No assessment assigned yet."}</p>
                    </div>
                  </div>
                  <div className="mt-4 rounded-3xl bg-slate-50 p-4">
                    <p className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-500">Feedback summary</p>
                    <p className="mt-2 text-sm leading-6 text-slate-700">
                      {child.submissionCount} submission{child.submissionCount === 1 ? "" : "s"} and {child.feedbackCount} feedback entr
                      {child.feedbackCount === 1 ? "y" : "ies"} recorded.
                    </p>
                    <p className="mt-2 text-sm text-slate-600">{child.latestFeedbackComment ?? "No teacher feedback has been added yet."}</p>
                  </div>
                  {child.latestProjectId ? (
                    <Link
                      href={`/app/projects/${child.latestProjectId}`}
                      className="mt-4 inline-flex rounded-full border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 transition hover:border-brand-300 hover:text-brand-900"
                    >
                      Open latest project workspace
                    </Link>
                  ) : null}
                </article>
              ))}
            </div>
          )}
        </div>
      </DashboardSection>

      <DashboardSection
        title="Quiz results"
        description="Parents can review quiz scores, AI grading summaries, and teacher feedback in read-only form for linked learners."
      >
        {linkedQuizResults.length === 0 ? (
          <EmptyState title="No linked learner quiz results yet" description="Quiz results will appear here after linked learners complete assigned quizzes." />
        ) : (
          <div className="space-y-4">
            {linkedQuizResults.map((child) => (
              <article key={child.studentId} className="rounded-[1.5rem] border border-slate-200 p-5">
                <h3 className="text-xl font-semibold text-ink">{child.studentName}</h3>
                {child.quizzes.length === 0 ? (
                  <p className="mt-3 text-sm text-slate-500">No quizzes assigned for this learner yet.</p>
                ) : (
                  <div className="mt-4 grid gap-4 xl:grid-cols-2">
                    {child.quizzes.slice(0, 6).map((quiz) => (
                      <div key={quiz.id} className="rounded-[1.25rem] bg-slate-50 p-4">
                        <p className="text-sm font-semibold text-ink">{quiz.title}</p>
                        <p className="mt-1 text-sm text-slate-500">
                          {quiz.subject} | Due {formatDate(quiz.dueDate)}
                        </p>
                        <p className="mt-2 text-sm text-slate-700">
                          {quiz.aiScore !== null ? `AI score ${quiz.aiScore.toFixed(1)}%.` : "Awaiting submission."}
                          {quiz.teacherComment ? ` Teacher feedback: ${quiz.teacherComment}` : ""}
                        </p>
                      </div>
                    ))}
                  </div>
                )}
              </article>
            ))}
          </div>
        )}
      </DashboardSection>

      <DashboardSection
        title="Upcoming deadlines"
        description="Parents can monitor due-soon and overdue lesson work in read-only form for each linked learner."
      >
        {childDeadlines.length === 0 ? (
          <EmptyState title="No linked learner deadlines yet" description="Once linked learners have due-dated lesson tasks, they will appear here." />
        ) : (
          <div className="space-y-4">
            {childDeadlines.map((child) => (
              <article key={child.studentId} className="rounded-[1.5rem] border border-slate-200 p-5">
                <h3 className="text-xl font-semibold text-ink">{child.studentName}</h3>
                {child.tasks.length === 0 ? (
                  <p className="mt-3 text-sm text-slate-500">No due-dated tasks for this learner yet.</p>
                ) : (
                  <div className="mt-4 grid gap-4 xl:grid-cols-2">
                    {child.tasks.slice(0, 4).map((task) => (
                      <div key={task.taskId} className="rounded-[1.25rem] bg-slate-50 p-4">
                        <p className="text-sm font-semibold text-ink">{task.taskTitle}</p>
                        <p className="mt-1 text-sm text-slate-500">
                          {task.programTitle} | {task.lessonTitle}
                        </p>
                        <p className="mt-2 text-sm text-slate-600">
                          {task.dueState.replace("_", " ")} | {task.dueDate ? `Due ${formatDate(task.dueDate)}` : "No due date"}
                        </p>
                      </div>
                    ))}
                  </div>
                )}
              </article>
            ))}
          </div>
        )}
      </DashboardSection>
    </AppShell>
  );
}
